name: 'Azure KeyVault Secrets'
description: 'Fetches azure KeyVault secrets and stores them in env variables as secrets'
author: '@theotow'
branding:
  icon: play
  color: green
inputs:
  key-vault-name:
    required: true
    description: 'name of the azure key vault'
  config:
    required: false
    description: 'github secret name to key vault secret name mapping'
    default: '{}'
runs:
  using: 'node16'
  main: 'dist/index.js'
